name: tempo
description: A minimalist, high-fidelity alarm clock app.
publish_to: "none"
version: 1.0.9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^17.2.0
  intl: ^0.19.0
  uuid: ^4.5.1
  provider: ^6.1.0
  http: ^1.2.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  audioplayers: ^6.1.0
  timezone: ^0.9.4
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
